Repository ethanmoffat/EndlessClient, pull requests merged in 2024-08, with the labels that each got.

#377 Add support MFX on Linux
  EndlessClient/Audio/MfxPlayer.cs
  README.md
Labels: feature

#378 Update eolib-dotnet to rc3
  EOLib.IO/EOLib.IO.csproj
  EOLib.Localization/EOLib.Localization.csproj
  EOLib/EOLib.csproj
  EOLib/PacketHandlers/NPC/NPCDeathHandler.cs
  EOLib/PacketHandlers/Trade/TradeOfferUpdateHandler.cs
  EndlessClient/EndlessClient.csproj
Labels: code enhancement

#379 fix: correct name notation
  EndlessClient/UIControls/CharacterInfoPanel.cs
Labels: bug

#380 Block character login keyboard shortcut when any dialogs are open
  EndlessClient/UIControls/CharacterInfoPanel.cs
Labels: bug

#358 Chat fixes
  EOLib/PacketHandlers/Chat/GroupChatHandler.cs
  EndlessClient/Audio/SoundEffectID.cs
  EndlessClient/Controllers/ChatController.cs
  EndlessClient/Controllers/LoginController.cs
  EndlessClient/HUD/Chat/ChatNotificationActions.cs
  EndlessClient/HUD/Chat/ChatPanelTab.cs
  EndlessClient/HUD/Panels/ChatPanel.cs
  EndlessClient/Subscribers/OtherCharacterEventSubscriber.cs
Labels: bug
